# Generated by Django 2.0 on 2019-11-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190912_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='mycode',
            field=models.URLField(blank=True, null=True),
        ),
    ]
