# Generated by Django 2.0 on 2019-11-02 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_myuser_mycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mycode', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='mycode',
        ),
        migrations.AddField(
            model_name='usercode',
            name='codeid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
