# Generated by Django 2.0 on 2019-11-02 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191102_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercode',
            old_name='codeid',
            new_name='user',
        ),
    ]
