# Generated by Django 2.0 on 2019-11-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191102_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercode',
            name='title',
            field=models.CharField(default='title', max_length=100),
            preserve_default=False,
        ),
    ]
