# Generated by Django 2.0 on 2019-11-05 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usercode_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='phone',
        ),
    ]
