# Generated by Django 2.0 on 2019-08-30 13:15

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_div', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('expiration_date', models.DateTimeField()),
                ('hw_type', models.CharField(choices=[('CODE', '코딩과제'), ('FILE', '제출과제'), ('MAIL', '메일전송')], default='CODE', max_length=10)),
                ('title', models.CharField(blank=True, max_length=30)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homework.Assignment')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('subject_no', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('class_div', models.CharField(blank=True, max_length=20)),
                ('subject_nm', models.CharField(blank=True, max_length=40)),
                ('shyr', models.CharField(blank=True, max_length=20)),
                ('prof_nm', models.CharField(blank=True, max_length=20)),
                ('class_nm', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-subject_no'],
            },
        ),
        migrations.CreateModel(
            name='FileSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('myfile', models.FileField(blank=True, null=True, upload_to='file_submit/%Y/%m/%d/')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homework.Assignment')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='class_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homework.Course'),
        ),
    ]
