# Generated by Django 2.0 on 2019-09-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmit',
            name='codeurl',
            field=models.URLField(blank=True),
        ),
    ]
