# Generated by Django 2.0 on 2019-09-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_codesubmit_codeurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='hw_type',
            field=models.CharField(choices=[('CODE', '코딩과제'), ('FILE', '제출과제')], default='CODE', max_length=10),
        ),
    ]
