# Generated by Django 2.0 on 2019-11-04 14:28

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
    ]
