# Generated by Django 2.0 on 2019-11-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_extracurricular_extra_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extracurricular',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='extracurricular',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
